[phases.setup]
nixPkgs = ["nodejs-20_x", "python3", "gcc", "pkg-config", "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "pixman"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"